export interface Config {
  REACT_APP_FIREBASE_CONFIG_API_KEY: string;
  REACT_APP_FIREBASE_CONFIG_AUTH_DOMAIN: string;
  REACT_APP_FIREBASE_CONFIG_DATABASE_URL: string;
  REACT_APP_FIREBASE_CONFIG_PROJECT_ID: string;
  REACT_APP_FIREBASE_CONFIG_STORAGE_BUCKET: string;
  REACT_APP_FIREBASE_CONFIG_MESSAGING_SENDER_ID: string;
  REACT_APP_FIREBASE_CONFIG_APP_ID: string;
}
