name: Build and run tests on PR
'on': pull_request
jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout merged code
        uses: actions/checkout@v2

      - name: Bootstrap
        run: npm run bootstrap

      - name: Build project
        run: npm run build
        env:
          REACT_APP_FIREBASE_CONFIG_API_KEY: ${{ secrets.REACT_APP_FIREBASE_CONFIG_API_KEY }}
          REACT_APP_FIREBASE_CONFIG_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_CONFIG_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_CONFIG_DATABASE_URL: ${{ secrets.REACT_APP_FIREBASE_CONFIG_DATABASE_URL }}
          REACT_APP_FIREBASE_CONFIG_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_CONFIG_PROJECT_ID }}
          REACT_APP_FIREBASE_CONFIG_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_CONFIG_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_CONFIG_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_CONFIG_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_CONFIG_APP_ID: ${{ secrets.REACT_APP_FIREBASE_CONFIG_APP_ID }}
          REACT_APP_FIREBASE_USE_EMULATORS: true

      - name: Start emulators
        run: npx firebase emulators:start &
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PIPELINE_GAME_DEV }}

      - name: Firestore rules test
        run: npm run test:firestore
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080

      - name: Run e2e test
        uses: cypress-io/github-action@v2
        with:
          working-directory: packages/game-app
          install: false
          wait-on: 'http://localhost:5000'
        env:
          CYPRESS_BASE_URL: http://localhost:5000
          FIREBASE_AUTH_EMULATOR_HOST: localhost:9099
          FIRESTORE_EMULATOR_HOST: localhost:8080
          REACT_APP_FIREBASE_CONFIG_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_CONFIG_PROJECT_ID }}


